### ISSUE TITLE
Chrome extension

### ISSUE THREAD

**Issue by Rakleed** [jeremiahlee/tab-tosser#2]
Please make extension for browsers on Chromium.

**Comment by jeremiahlee** [comment]
@Rakleed Thank you for reaching out. Tab Tosser is both intentionally not available for Chrome and not easily possible in Chrome.

Chrome has not implemented the [`lastAccessed`](https://developer.mozilla.org/en-US/docs/Mozilla/Add-ons/WebExtensions/API/tabs/Tab) property on `tabs.Tab`. This means I would have to implement equivalent functionality, which is possible, in order to make Tab Tosser available for Chrome.

More importantly, I do not want Tab Tosser to be made available for Chrome because [Google’s predominant business model is unethical][1]. I do not want Tab Tosser to be made available for Chromium-powered browsers because [the Web as a platform is harmed by a browser monoculture][2]. (This in enforceable because Tab Tosser is [_viewable_ source, but not open source](https://github.com/jeremiahlee/tab-tosser/edit/master/LICENSE.md).)

[1]: https://2018.ar.al/notes/spyware-2.0/ "Spyware 2.0"
[2]: https://blog.mozilla.org/blog/2018/12/06/goodbye-edge/ "Goodbye, EdgeHTML"
